In [9]:
import matplotlib.pyplot as plt

import pandas as pd


df = pd.read_csv("/gpfs/data/schambralab/quantitativeRehabilitation/__lab_member_homes/victor/cvfm4rehab/data/public/cleaned_metadata.csv")

In [10]:
df.head()

,id,is_in_strokerehab_test_set,path_v,patient,stroke,activity,fps,height,width,duration_s,path_l,nlabels,subsampled_test_set
0,S00027_feeding1_1,False,S00027/S00027_feeding1_1.avi,S00027,True,feeding,60.0,352,736,70.500,S00027/S00027_feeding1_1.csv,4231,False
1,S00027_combing1_2,False,S00027/S00027_combing1_2.avi,S00027,True,combing,60.0,352,736,19.183,S00027/S00027_combing1_2.csv,1152,False
2,S00027_glasses1_1,False,S00027/S00027_glasses1_1.avi,S00027,True,glasses,60.0,352,736,21.600,S00027/S00027_glasses1_1.csv,1297,False
3,S00027_face wash3_2,False,S00027/S00027_face wash3_2.avi,S00027,True,face wash,60.0,352,736,60.350,S00027/S00027_face wash3_2.csv,3622,False
4,S00027_glasses5_2,False,S00027/S00027_glasses5_2.avi,S00027,True,glasses,60.0,352,736,14.183,S00027/S00027_glasses5_2.csv,852,False

In [11]:
df = df[df['is_in_strokerehab_test_set']]

In [12]:
# Which activities?
print(df['activity'].unique())
# Which patients?
print(df['patient'].unique())

['face wash' 'shelf right side' 'feeding' 'glasses' 'brushing' 'combing'
 'shelf left side' 'drinking' 'RTT left side' 'deodrant' 'RTT right side']
['S00047' 'S00044' 'S00042' 'S00039' 'S0004' 'S00017' 'S00037' 'S00026']

In [ ]:
# s47=mild, s44=moderate, s42=mild, s39=moderate, s4=moderate, s17=moderate, s37=mild, s26=mild

In [13]:
df[(df['activity'] == 'face wash') & (df['patient'] == 'S00047')]

,id,is_in_strokerehab_test_set,path_v,patient,stroke,activity,fps,height,width,duration_s,path_l,nlabels,subsampled_test_set
922,S00047_face wash3_1,True,S00047/S00047_face wash3_1.mkv,S00047,True,face wash,60.0,704,1088,29.987,S00047/S00047_face wash3_1.csv,1800,False
938,S00047_face wash2_2,True,S00047/S00047_face wash2_2.mkv,S00047,True,face wash,60.0,704,1088,28.154,S00047/S00047_face wash2_2.csv,1690,False
951,S00047_face wash5_2,True,S00047/S00047_face wash5_2.mkv,S00047,True,face wash,60.0,1088,704,31.721,S00047/S00047_face wash5_2.csv,1904,False
955,S00047_face wash2_1,True,S00047/S00047_face wash2_1.mkv,S00047,True,face wash,60.0,1088,704,28.154,S00047/S00047_face wash2_1.csv,1690,False
957,S00047_face wash1_1,True,S00047/S00047_face wash1_1.mkv,S00047,True,face wash,60.0,1088,704,35.938,S00047/S00047_face wash1_1.csv,2157,False
960,S00047_face wash5_1,True,S00047/S00047_face wash5_1.mkv,S00047,True,face wash,60.0,704,1088,31.771,S00047/S00047_face wash5_1.csv,1907,False
961,S00047_face wash4_2,True,S00047/S00047_face wash4_2.mkv,S00047,True,face wash,60.0,1088,704,35.672,S00047/S00047_face wash4_2.csv,2141,False
967,S00047_face wash3_2,True,S00047/S00047_face wash3_2.mkv,S00047,True,face wash,60.0,1088,704,29.987,S00047/S00047_face wash3_2.csv,1800,False
968,S00047_face wash4_1,True,S00047/S00047_face wash4_1.mkv,S00047,True,face wash,60.0,704,1088,35.705,S00047/S00047_face wash4_1.csv,2143,False
997,S00047_face wash1_2,True,S00047/S00047_face wash1_2.mkv,S00047,True,face wash,60.0,704,1088,35.938,S00047/S00047_face wash1_2.csv,2157,False

In [4]:
df['id'].tolist()

['S00027_feeding1_1',
 'S00027_combing1_2',
 'S00027_glasses1_1',
 'S00027_face wash3_2',
 'S00027_glasses5_2',
 'S00027_drinking5_2',
 'S00027_brushing2_2',
 'S00027_feeding4_2',
 'S00027_glasses5_1',
 'S00027_glasses4_2',
 'S00027_combing2_2',
 'S00027_combing4_2',
 'S00027_brushing4_2',
 'S00027_combing2_1',
 'S00027_feeding4_1',
 'S00027_brushing1_2',
 'S00027_feeding5_2',
 'S00027_glasses1_2',
 'S00027_feeding2_1',
 'S00027_face wash4_1',
 'S00027_brushing5_2',
 'S00027_combing3_2',
 'S00027_drinking2_1',
 'S00027_deodrant1_1',
 'S00027_face wash4_2',
 'S00027_deodrant5_1',
 'S00027_drinking3_2',
 'S00027_glasses3_1',
 'S00027_face wash5_1',
 'S00027_face wash5_2',
 'S00027_face wash3_1',
 'S00027_shelf left side2_1',
 'S00027_drinking4_1',
 'S00027_brushing2_1',
 'S00027_RTT left side1_1',
 'S00027_drinking4_2',
 'S00027_deodrant3_2',
 'S00027_RTT left side2_1',
 'S00027_drinking1_1',
 'S00027_RTT left side4_1',
 'S00027_glasses4_1',
 'S00027_combing3_1',
 'S00027_RTT left side4_2',
 'S00027_face wash2_1',
 'S00027_deodrant3_1',
 'S00027_RTT left side5_1',
 'S00027_face wash1_2',
 'S00027_drinking5_1',
 'S00027_combing5_1',
 'S00027_feeding5_1',
 'S00027_combing4_1',
 'S00027_deodrant5_2',
 'S00027_brushing3_1',
 'S00027_deodrant2_2',
 'S00027_face wash1_1',
 'S00027_shelf left side3_2',
 'S00027_drinking1_2',
 'S00027_combing1_1',
 'S00023_drinking4_1',
 'S00027_brushing1_1',
 'S00023_brushing3_2',
 'S00023_face wash2_1',
 'S00027_drinking2_2',
 'S00023_deodrant2_2',
 'S00023_feeding2_1',
 'S00027_RTT left side5_2',
 'S00023_feeding1_2',
 'S00027_deodrant1_2',
 'S00027_glasses2_1',
 'S00023_RTT left side5_2',
 'S00027_RTT left side3_1',
 'S00027_feeding1_2',
 'S00023_RTT left side1_1',
 'S00027_glasses2_2',
 'S00023_feeding1_1',
 'S00027_feeding3_1',
 'S00023_glasses3_2',
 'S00027_RTT left side2_2',
 'S00023_face wash1_1',
 'S00027_face wash2_2',
 'S00023_drinking4_2',
 'S00027_brushing5_1',
 'S00027_deodrant2_1',
 'S00023_brushing4_2',
 'S00023_combing2_1',
 'S00027_deodrant4_2',
 'S00023_combing4_1',
 'S00027_combing5_2',
 'S00023_brushing2_1',
 'S00023_combing3_1',
 'S00027_brushing4_1',
 'S00027_shelf left side1_2',
 'S00023_feeding3_1',
 'S00023_RTT left side4_2',
 'S00023_combing1_2',
 'S00023_shelf left side3_2',
 'S00023_deodrant1_1',
 'S00023_brushing4_1',
 'S00027_glasses3_2',
 'S00023_drinking1_2',
 'S00023_face wash1_2',
 'S00027_feeding3_2',
 'S00027_feeding2_2',
 'S00023_face wash3_1',
 'S00023_deodrant4_1',
 'S00027_brushing3_2',
 'S00027_shelf left side1_1',
 'S00027_RTT left side1_2',
 'S00027_RTT left side3_2',
 'S00023_shelf left side2_2',
 'S00027_drinking3_1',
 'S00023_shelf left side5_2',
 'S00023_deodrant5_2',
 'S00023_combing2_2',
 'S00027_deodrant4_1',
 'S00023_combing1_1',
 'S00027_shelf left side2_2',
 'S00023_glasses4_2',
 'S00023_combing4_2',
 'S00023_glasses2_1',
 'S00027_shelf left side3_1',
 'S00023_face wash2_2',
 'S00023_feeding5_2',
 'S00023_glasses5_1',
 'S00023_brushing2_2',
 'S00023_deodrant2_1',
 'S00023_deodrant3_2',
 'S00023_drinking1_1',
 'S00023_RTT left side1_2',
 'S00023_combing3_2',
 'S00023_shelf left side1_1',
 'S00023_drinking3_1',
 'S00023_brushing5_1',
 'S00023_brushing1_2',
 'S00023_combing5_2',
 'S00023_brushing3_1',
 'S00023_feeding5_1',
 'S00023_feeding4_1',
 'S00023_shelf left side3_1',
 'S00023_glasses2_2',
 'S00023_RTT left side2_1',
 'S00023_shelf left side2_1',
 'S00023_face wash5_1',
 'S00023_RTT left side3_2',
 'S00023_drinking3_2',
 'S00023_face wash4_1',
 'S00023_glasses4_1',
 'S00023_drinking2_2',
 'S00023_drinking5_2',
 'S00023_RTT left side4_1',
 'S00023_feeding2_2',
 'S00023_face wash5_2',
 'S00023_glasses1_1',
 'S00023_face wash4_2',
 'S00023_brushing1_1',
 'S00023_RTT left side2_2',
 'S00023_combing5_1',
 'S00023_shelf left side5_1',
 'S00019_deodrant3_1',
 'S00023_drinking5_1',
 'S00023_drinking2_1',
 'S00019_shelf left side4_1',
 'S00023_shelf left side4_1',
 'S00023_shelf left side1_2',
 'S00023_RTT left side5_1',
 'S00023_deodrant5_1',
 'S00019_shelf left side1_2',
 'S00023_glasses5_2',
 'S00023_deodrant4_2',
 'S00019_shelf left side3_1',
 'S00023_feeding3_2',
 'S00019_deodrant1_1',
 'S00019_face wash2_2',
 'S00023_brushing5_2',
 'S00019_deodrant2_1',
 'S00019_combing2_2',
 'S00019_combing4_2',
 'S00023_shelf left side4_2',
 'S00019_drinking4_1',
 'S00019_drinking5_1',
 'S00023_glasses3_1',
 'S00023_deodrant1_2',
 'S00019_RTT left side5_1',
 'S00019_deodrant2_2',
 'S00019_drinking1_2',
 'S00019_brushing3_2',
 'S00019_RTT left side4_1',
 'S00019_face wash5_1',
 'S00023_deodrant3_1',
 'S00019_brushing1_2',
 'S00019_glasses4_2',
 'S00019_feeding3_2',
 'S00023_glasses1_2',
 'S00019_glasses3_2',
 'S00019_shelf left side5_2',
 'S00019_brushing2_1',
 'S00019_glasses3_1',
 'S00019_shelf left side3_2',
 'S00019_RTT left side1_2',
 'S00019_glasses1_2',
 'S00019_glasses5_2',
 'S00019_combing1_2',
 'S00019_drinking1_1',
 'S00019_deodrant3_2',
 'S00019_feeding1_1',
 'S00019_deodrant4_2',
 'S00019_glasses5_1',
 'S00019_brushing4_1',
 'S00019_deodrant5_2',
 'S00019_feeding4_1',
 'S00019_RTT left side3_1',
 'S00019_brushing3_1',
 'S00019_feeding4_2',
 'S00019_combing4_1',
 'S00019_face wash3_1',
 'S00019_feeding5_1',
 'S00019_shelf left side5_1',
 'S00019_face wash5_2',
 'S00019_RTT left side4_2',
 'S00019_combing3_1',
 'S00019_brushing5_2',
 'S00023_RTT left side3_1',
 'S00019_deodrant4_1',
 'S00019_combing5_1',
 'S00023_face wash3_2',
 'S00019_face wash1_1',
 'S00019_drinking3_1',
 'S00019_drinking5_2',
 'S00019_drinking2_1',
 'S00019_face wash3_2',
 'S00023_feeding4_2',
 'S00019_brushing5_1',
 'S00019_brushing4_2',
 'S00019_glasses1_1',
 'S00019_feeding2_2',
 'S00019_face wash4_2',
 'S00019_RTT left side3_2',
 'S00019_RTT left side2_1',
 'S00019_drinking2_2',
 'S00019_deodrant1_2',
 'S00019_combing3_2',
 'S00019_shelf left side1_1',
 'S00019_RTT left side1_1',
 'S00019_feeding3_1',
 'S00019_RTT left side2_2',
 'S00019_glasses2_1',
 'S00019_combing1_1',
 'S00019_face wash2_1',
 'S0007_deodrant3_2',
 'S00019_face wash1_2',
 'S0007_deodrant2_1',
 'S00019_glasses4_1',
 'S00019_brushing2_2',
 'S0007_face wash4_1',
 'S00019_drinking4_2',
 'S0007_drinking4_1',
 'S0007_combing2_1',
 'S00019_shelf left side4_2',
 'S00019_combing5_2',
 'S00019_RTT left side5_2',
 'S0007_glasses5_2',
 'S00019_glasses2_2',
 'S0007_glasses2_1',
 'S0007_face wash1_2',
 'S00019_face wash4_1',
 'S00019_feeding2_1',
 'S0007_RTT right side5_2',
 'S0007_deodrant1_2',
 'S00019_shelf left side2_2',
 'S0007_brushing3_2',
 'S0007_drinking3_2',
 'S0007_brushing2_1',
 'S0007_shelf right side1_1',
 'S00019_drinking3_2',
 'S0007_combing5_1',
 'S0007_combing5_2',
 'S0007_RTT right side5_1',
 'S00019_shelf left side2_1',
 'S0007_shelf right side2_1',
 'S0007_brushing4_1',
 'S0007_RTT right side1_1',
 'S0007_shelf right side5_2',
 'S0007_brushing1_2',
 'S0007_face wash2_2',
 'S0007_combing1_2',
 'S0007_glasses4_1',
 'S00019_brushing1_1',
 'S0007_combing3_2',
 'S0007_shelf right side5_1',
 'S0007_RTT right side2_2',
 'S0007_deodrant5_1',
 'S0007_shelf right side3_2',
 'S0007_drinking1_2',
 'S0007_combing3_1',
 'S0007_drinking2_1',
 'S0007_face wash3_1',
 'S0007_RTT right side3_1',
 'S0007_feeding1_1',
 'S00019_feeding1_2',
 'S0007_feeding2_2',
 'S0007_combing1_1',
 'S0007_brushing2_2',
 'S0007_shelf right side3_1',
 'S0007_face wash5_2',
 'S00019_deodrant5_1',
 'S0007_drinking5_1',
 'S0007_shelf right side2_2',
 'S0007_face wash3_2',
 'S0007_face wash1_1',
 'S0007_RTT right side1_2',
 'S0007_feeding4_2',
 'S0007_deodrant1_1',
 'S0007_feeding4_1',
 'S0007_glasses3_2',
 'S0007_face wash5_1',
 'S0007_combing2_2',
 'S0007_glasses1_1',
 'S0007_brushing5_2',
 'S0007_drinking4_2',
 'S0007_shelf right side4_2',
 'S0007_feeding5_1',
 'S0007_deodrant2_2',
 'S0007_drinking5_2',
 'S0007_RTT right side4_1',
 'S0007_RTT right side4_2',
 'S00019_combing2_1',
 'S0007_glasses2_2',
 'S0007_feeding5_2',
 'S0007_brushing5_1',
 'C00020_face wash4_2',
 'S0007_combing4_2',
 'S0007_drinking2_2',
 'S0007_drinking3_1',
 'S0007_glasses4_2',
 'S0007_face wash2_1',
 'S0007_brushing4_2',
 'S0007_RTT right side3_2',
 'S0007_drinking1_1',
 'S0007_RTT right side2_1',
 'S0007_feeding1_2',
 'S0007_deodrant4_1',
 'S0007_combing4_1',
 'S0007_deodrant5_2',
 'S0007_feeding3_2',
 'C00020_glasses1_1',
 'S0007_shelf right side1_2',
 'C00020_drinking4_1',
 'C00020_drinking3_1',
 'C00020_deodrant5_1',
 'C00020_glasses3_2',
 'C00020_glasses4_1',
 'C00020_RTT right side1_2',
 'C00020_shelf right side2_2',
 'S0007_brushing3_1',
 'C00020_drinking1_1',
 'C00020_glasses2_1',
 'C00020_drinking3_2',
 'C00020_drinking4_2',
 'C00020_combing1_2',
 'S0007_brushing1_1',
 'S0007_deodrant4_2',
 'C00020_RTT right side2_2',
 'S0007_face wash4_2',
 'C00020_brushing3_2',
 'C00020_combing1_1',
 'C00020_RTT left side3_2',
 'S0007_deodrant3_1',
 'C00020_RTT left side2_1',
 'S0007_shelf right side4_1',
 'C00020_deodrant4_2',
 'C00020_RTT left side2_2',
 'S0007_glasses1_2',
 'C00020_glasses0_1',
 'C00020_face wash2_2',
 'C00020_brushing1_1',
 'C00020_RTT left side1_2',
 'C00020_RTT right side5_1',
 'C00020_face wash5_2',
 'C00020_brushing4_2',
 'C00020_RTT left side5_2',
 'C00020_feeding2_1',
 'S0007_feeding3_1',
 'C00020_face wash1_2',
 'C00020_shelf right side2_1',
 'C00020_RTT left side4_2',
 'C00020_shelf right side4_2',
 'C00020_glasses3_1',
 'C00020_combing2_1',
 'C00020_glasses2_2',
 'C00020_shelf right side4_1',
 'C00020_feeding1_1',
 'C00020_deodrant5_2',
 'C00020_brushing2_2',
 'C00020_deodrant3_1',
 'C00020_deodrant1_2',
 'C00020_face wash1_1',
 'C00020_feeding3_1',
 'C00020_RTT right side2_1',
 'S0007_feeding2_1',
 'C00020_RTT right side3_1',
 'C00020_brushing3_1',
 'C00020_feeding5_2',
 'S0007_glasses3_1',
 'C00020_feeding2_2',
 'C00020_shelf right side3_1',
 'S0007_glasses5_1',
 'C00020_feeding4_1',
 'C00020_shelf right side1_2',
 'C00020_feeding4_2',
 'C00020_glasses1_2',
 'C00020_feeding5_1',
 'C00020_brushing2_1',
 'C00020_glasses5_2',
 'C00020_RTT left side3_1',
 'C00020_deodrant2_1',
 'C00020_shelf right side5_1',
 'C00020_deodrant2_2',
 'C00020_brushing5_2',
 'C00020_RTT left side1_1',
 'C00020_drinking1_2',
 'C00020_shelf right side1_1',
 'C00020_brushing4_1',
 'C00020_face wash3_2',
 'C00020_RTT left side5_1',
 'C0004_shelf left side1_1',
 'C00020_deodrant3_2',
 'C00020_face wash2_1',
 'C0004_feeding4_2',
 'C00020_combing2_2',
 'C0004_deodrant3_1',
 'C00020_brushing1_2',
 'C00020_shelf right side5_2',
 'C00020_drinking5_2',
 'C00020_face wash5_1',
 'C00020_glasses4_2',
 'C00020_deodrant4_1',
 'C00020_RTT right side4_1',
 'C0004_RTT left side5_2',
 'C00020_RTT right side3_2',
 'C00020_deodrant1_1',
 'C0004_shelf right side5_1',
 'C00020_RTT right side5_2',
 'C00020_drinking2_1',
 'C00020_drinking2_2',
 'C0004_glasses5_2',
 'C00020_glasses0_2',
 'C0004_combing2_1',
 'C00020_face wash3_1',
 'C0004_drinking4_2',
 'C00020_RTT right side4_2',
 'C0004_RTT left side4_2',
 'C0004_deodrant3_2',
 'C00020_brushing5_1',
 'C0004_feeding5_2',
 'C0004_brushing5_1',
 'C0004_RTT left side2_2',
 'C00020_feeding1_2',
 'C00020_face wash4_1',
 'C0004_shelf right side3_1',
 'C00020_drinking5_1',
 'C0004_combing5_1',
 'C0004_drinking3_1',
 'C0004_deodrant1_2',
 'C0004_shelf right side1_1',
 'C0004_glasses5_1',
 'C0004_brushing1_2',
 'C0004_shelf right side3_2',
 'C0004_drinking4_1',
 'C00020_RTT left side4_1',
 'C0004_RTT right side4_2',
 'C00020_feeding3_2',
 'C0004_RTT left side3_2',
 'C00020_RTT right side1_1',
 'C0004_feeding5_1',
 'C0004_shelf left side1_2',
 'C0004_drinking3_2',
 'C0004_shelf left side3_2',
 'C0004_glasses3_2',
 'C00020_glasses5_1',
 'C0004_RTT right side2_1',
 'C0004_feeding2_1',
 'C0004_RTT left side1_1',
 'C00020_shelf right side3_2',
 'C0004_RTT left side1_2',
 'C0004_shelf left side2_2',
 'C0004_shelf right side4_1',
 'C0004_RTT right side3_2',
 'C0004_glasses4_2',
 'C0004_shelf left side5_2',
 'C0004_face wash1_2',
 'C0004_shelf left side2_1',
 'C0004_shelf right side2_1',
 'C0004_RTT left side2_1',
 'C0004_face wash4_1',
 'C0004_shelf left side5_1',
 'C0004_deodrant5_2',
 'C0004_drinking2_2',
 'C0004_glasses3_1',
 'C0004_face wash1_1',
 'C0004_RTT left side5_1',
 'C0004_shelf left side4_2',
 'C0004_brushing3_2',
 'C0004_shelf right side4_2',
 'C0004_shelf right side5_2',
 'C0004_deodrant5_1',
 'C0004_combing3_1',
 'C0004_brushing2_2',
 'C0004_feeding2_2',
 'C0004_drinking5_1',
 'C0004_glasses2_2',
 'C0004_combing1_1',
 'C0004_face wash5_1',
 'C0004_drinking2_1',
 'C0004_combing4_2',
 'C0004_drinking5_2',
 'C0004_shelf left side4_1',
 'C0004_combing5_2',
 'C0004_combing3_2',
 'C0004_shelf left side3_1',
 'C0004_combing4_1',
 'C0004_glasses4_1',
 'C0004_feeding1_2',
 'C0004_RTT left side4_1',
 'C0004_drinking1_2',
 'C0004_combing1_2',
 'C0004_shelf right side1_2',
 'C0004_RTT right side3_1',
 'C0004_deodrant4_2',
 'C0004_RTT right side2_2',
 'C0004_face wash2_1',
 'C0004_brushing2_1',
 'C0004_deodrant1_1',
 'C0004_feeding4_1',
 'C0004_glasses1_2',
 'C0004_face wash3_1',
 'C0004_deodrant2_1',
 'C0004_face wash4_2',
 'C0004_RTT right side4_1',
 'C0004_feeding3_1',
 'C0004_RTT right side5_2',
 'C0004_glasses1_1',
 'C0004_face wash5_2',
 'C0004_deodrant4_1',
 'C0004_RTT right side1_1',
 'S00016_drinking3_1',
 'C0004_brushing3_1',
 'C0004_drinking1_1',
 'C0004_face wash2_2',
 'C0004_RTT left side3_1',
 'C0004_shelf right side2_2',
 'S00016_drinking3_2',
 'S00016_combing2_2',
 'C0004_brushing4_1',
 'S00016_face wash3_1',
 'S00016_face wash4_2',
 'S00016_combing5_1',
 'C0004_feeding1_1',
 'S00016_RTT right side4_2',
 'S00016_feeding2_2',
 'C0004_RTT right side1_2',
 'S00016_glasses2_1',
 'C0004_deodrant2_2',
 'S00016_combing5_2',
 'S00016_brushing3_2',
 'C0004_RTT right side5_1',
 'S00016_RTT right side2_1',
 'C0004_feeding3_2',
 'S00016_drinking2_2',
 'S00016_drinking1_2',
 'S00016_brushing5_1',
 'S00016_shelf right side3_1',
 'S00016_face wash2_2',
 'C0004_combing2_2',
 'S00016_combing1_2',
 'C0004_brushing4_2',
 'S00016_feeding4_1',
 'S00016_glasses5_2',
 'S00016_RTT right side1_2',
 'S00016_face wash2_1',
 'C0004_brushing5_2',
 'S00016_face wash4_1',
 'C0004_brushing1_1',
 'S00016_brushing1_2',
 'S00016_shelf right side4_2',
 'S00016_combing3_1',
 'C0004_glasses2_1',
 'S00016_shelf right side2_1',
 'C0004_face wash3_2',
 'S00016_RTT right side1_1',
 'S00016_combing3_2',
 'S00016_drinking4_1',
 'S00016_brushing2_1',
 'S00016_glasses1_2',
 'S00016_drinking2_1',
 'S00016_face wash6_1',
 'S00016_glasses5_1',
 'S00016_RTT right side3_1',
 'S00016_glasses4_1',
 'S00016_glasses4_2',
 'S00016_feeding1_2',
 'S00016_combing4_1',
 'S00016_RTT right side5_2',
 'S00016_feeding3_2',
 'S00016_shelf right side1_1',
 'S00016_feeding5_1',
 'S00016_shelf right side3_2',
 'S00016_drinking5_2',
 'S00016_drinking4_2',
 'S00016_combing2_1',
 'S00016_feeding4_2',
 'S00016_brushing5_2',
 'S00016_deodrant1_2',
 'S00016_face wash3_2',
 'S00016_combing1_1',
 'S00016_shelf right side5_1',
 'S00016_glasses2_2',
 'S00016_deodrant1_1',
 'S00016_face wash5_1',
 'S00016_deodrant3_1',
 'S00016_shelf right side2_2',
 'S00016_glasses1_1',
 'S00016_RTT right side3_2',
 'S00016_deodrant2_1',
 'S00016_shelf right side5_2',
 'S00016_brushing3_1',
 'S00016_feeding2_1',
 'S00016_glasses3_1',
 'S00016_drinking1_1',
 'S00016_brushing4_1',
 'S00016_brushing2_2',
 'S00054_shelf left side3_2',
 'S00016_face wash5_2',
 'S00054_feeding1_2',
 'S00016_feeding3_1',
 'S00016_deodrant5_1',
 'S00016_RTT right side2_2',
 'S00016_combing4_2',
 'S00016_RTT right side5_1',
 'S00016_RTT right side4_1',
 'S00016_shelf right side4_1',
 'S00016_brushing4_2',
 'S00016_brushing1_1',
 'S00054_RTT left side2_1',
 'S00016_deodrant5_2',
 'S00054_deodrant1_1',
 'S00016_feeding1_1',
 'S00016_deodrant3_2',
 'S00054_RTT left side1_2',
 'S00054_shelf left side1_1',
 'S00054_RTT left side5_1',
 'S00054_combing1_2',
 'S00016_feeding5_2',
 'S00054_shelf left side3_1',
 'S00016_glasses3_2',
 'S00054_RTT left side5_2',
 'S00012_brushing3_1',
 'S00054_feeding2_1',
 'S00054_feeding5_1',
 'S00054_feeding4_1',
 'S00054_feeding5_2',
 'S00016_shelf right side1_2',
 'S00016_deodrant4_2',
 'S00054_feeding1_1',
 'S00016_drinking5_1',
 'S00054_RTT left side3_2',
 'S00054_RTT left side1_1',
 'S00054_feeding3_2',
 'S00054_shelf left side4_2',
 'S00054_feeding3_1',
 'S00054_deodrant1_2',
 'S00054_drinking1_1',
 'S00054_shelf left side2_1',
 'S00054_RTT left side4_1',
 'S00054_combing1_1',
 'S00054_feeding2_2',
 'S00054_brushing1_1',
 'S00016_deodrant2_2',
 'S00012_brushing2_1',
 'S00054_feeding4_2',
 'S00012_face wash5_1',
 'S00054_RTT left side3_1',
 'S00016_deodrant4_1',
 'S00054_brushing1_2',
 'S00016_face wash6_2',
 'S00012_shelf right side4_2',
 'S00054_shelf left side2_2',
 'S00012_shelf right side4_1',
 'S00012_feeding1_1',
 'S00012_glasses4_2',
 'S00054_shelf left side5_2',
 'S00012_RTT right side2_2',
 'S00054_glasses1_2',
 'S00012_face wash1_1',
 'S00012_combing2_2',
 'S00012_face wash2_1',
 'S00012_shelf right side3_2',
 'S00012_glasses1_1',
 'S00012_drinking5_2',
 'S00012_brushing5_1',
 'S00012_feeding5_2',
 'S00012_feeding2_1',
 'S00054_shelf left side1_2',
 'S00012_drinking2_1',
 'S00012_drinking1_1',
 'S00054_RTT left side2_2',
 'S00012_face wash2_2',
 'S00012_RTT right side3_2',
 'S00012_face wash4_2',
 'S00012_glasses2_2',
 'S00012_RTT right side5_1',
 'S00012_combing5_1',
 'S00012_feeding4_2',
 'S00012_shelf right side2_2',
 'S00012_feeding1_2',
 'S00012_deodrant5_2',
 'S00012_combing4_1',
 'S00054_RTT left side4_2',
 'S00012_shelf right side5_1',
 'S00012_drinking4_1',
 'S00054_glasses1_1',
 'S00012_RTT right side5_2',
 'S00012_brushing4_1',
 'S00012_glasses2_1',
 'S00012_shelf right side2_1',
 'S00012_shelf right side1_1',
 'S00012_combing4_2',
 'S00012_RTT right side1_2',
 'S00012_drinking3_1',
 'S00012_glasses5_1',
 'S00012_face wash1_2',
 'S00012_RTT right side3_1',
 'S00012_combing1_1',
 'S00012_combing1_2',
 'S00012_deodrant1_2',
 'S00012_glasses1_2',
 'S00012_shelf right side1_2',
 'S00012_brushing1_2',
 'S00012_RTT right side2_1',
 'S00012_feeding2_2',
 'S00012_deodrant4_1',
 'S00012_face wash3_2',
 'S00012_deodrant2_2',
 'S00012_shelf right side3_1',
 'S00012_deodrant2_1',
 'S00012_deodrant5_1',
 'S00012_brushing1_1',
 'S00012_drinking2_2',
 'S00012_deodrant1_1',
 'S00012_face wash4_1',
 'S00012_deodrant4_2',
 'S00012_RTT right side4_1',
 'S00012_shelf right side5_2',
 'S00012_feeding4_1',
 'S00012_feeding5_1',
 'S00012_brushing5_2',
 'S00012_glasses3_2',
 'S00054_drinking1_2',
 'S00012_RTT right side4_2',
 'S00012_drinking4_2',
 'S00055_shelf left side5_1',
 'S00012_combing2_1',
 'S00012_face wash5_2',
 'S00012_brushing2_2',
 'S00012_brushing3_2',
 'S00012_feeding3_2',
 'S00012_glasses3_1',
 'S00055_combing1_1',
 'S00012_face wash3_1',
 'S00055_glasses1_2',
 'S00012_combing3_2',
 'S00012_combing5_2',
 'S00012_drinking3_2',
 'S00012_glasses4_1',
 'S00055_RTT left side1_1',
 'S00012_brushing4_2',
 'S00012_combing3_1',
 'S00012_glasses5_2',
 'S00055_shelf left side5_2',
 'S00012_deodrant3_2',
 'S00055_shelf left side4_1',
 'S00055_glasses1_1',
 'S00054_face wash1_1',
 'S00055_shelf left side4_2',
 'S00055_RTT left side3_1',
 'S00055_deodrant1_2',
 'S00055_RTT left side5_2',
 'S00012_deodrant3_1',
 'S00055_shelf left side3_1',
 'S00055_RTT left side2_2',
 'S00055_face wash1_2',
 'S00055_shelf left side2_2',
 'S00055_face wash1_1',
 'S00012_RTT right side1_1',
 'S00012_drinking1_2',
 'S00055_RTT left side5_1',
 'S00055_RTT left side1_2',
 'S00054_face wash1_2',
 'S00055_shelf left side1_2',
 'S00055_shelf left side2_1',
 'S0006_drinking5_1',
 'S0006_glasses2_1',
 'S00055_drinking1_2',
 'S0006_deodrant5_1',
 'S00055_shelf left side3_2',
 'S00055_feeding1_1',
 'S00012_drinking5_1',
 'S00055_shelf left side1_1',
 'S0006_feeding1_1',
 'S00055_RTT left side4_1',
 'S0006_brushing2_2',
 'S00055_deodrant1_1',
 'S00055_RTT left side4_2',
 'S00055_combing1_2',
 'S00054_shelf left side5_1',
 'S0006_RTT right side1_2',
 'S00055_brushing1_2',
 'S0006_drinking5_2',
 'S0006_RTT right side5_2',
 'S0006_shelf right side1_2',
 'S0006_combing4_2',
 'S00055_RTT left side3_2',
 'S0006_drinking2_1',